NBA_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static, serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', RedirectView.as_view(url='home/')),
] + staticfiles_urlpatterns()

home/urls.py
from django.contrib import admin
from django.urls import path

from .views import HomeView, PlayerDetail, InactiveSearch

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('player-detail/<str:search_string>', PlayerDetail.as_view(), name='player_detail'),
    path('archive-search/', InactiveSearch.as_view(), name='inactive_search')
]

home/models.py
from django.db import models

# Create your models here.
class PlayerSearches(models.Model):
    
    player = models.CharField(max_length=100)
    search_count = models.IntegerField()
    
    def __str__(self):
        return self.player

home/forms.py
from django import forms

class SearchByNameForm(forms.Form):
    
    player_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        "class": "form-control",
        "type": "text",
        "id": "player_name",
        "placeholder": "Enter an active players name to get started",
        "aria-describedby": "basic-addon2"
    }), label = "Player Name");
    

home/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.html import strip_tags
from django.shortcuts import reverse
from django.conf import settings
from django.core.paginator import Paginator
from django.contrib import messages

from nba_api.stats.static import players
from nba_api.stats.endpoints import playercareerstats

from .forms import SearchByNameForm
from .models import PlayerSearches

from pathlib import Path

import requests
import json
import shutil
import re
# Create your views here.

class HomeView(View):
    
    template_name = 'home/home.html'
    
    def get(self, request, *args, **kwargs):
        
        form = SearchByNameForm()
        
        players = PlayerSearches.objects.all().order_by('-search_count')[:3]
        
        players_dict = {}
                
        for player in players:
           players_dict[player.player] = {
               'url': f"/static/player_imgs/{player.player.split()[0]}_{player.player.split()[1]}.png",
               'searches': player.search_count
           }
                       
        if 'search' in request.GET:
            
            player_name = strip_tags(request.GET['player_name'])
            
            return HttpResponseRedirect(reverse('home:player_detail', args=(player_name,)))
        
        context = {
            'players': players_dict,
            'form': SearchByNameForm
        }
        
        return render(request, self.template_name, context=context)

class PlayerDetail(View):
    
    template_name = 'home/player_detail.html'
    
    def get(self, request, *args, **kwargs):
        
        players_dict_with_stats = {}
        
        players_dict = players.get_players()
                
        player_to_get = [player for player in players_dict if player['full_name'] == kwargs['search_string']]
                
        if player_to_get != []:
            player_obj_search = PlayerSearches.objects.filter(player=player_to_get[0]['full_name'])
                        
            if player_obj_search:
                current_search_count = player_obj_search[0].search_count
                player_obj_search.update(search_count = current_search_count + 1)
            else:
                PlayerSearches.objects.create(player=player_to_get[0]['full_name'], search_count=1)
            
            if player_to_get[0]['is_active'] == False:
                player_stats = playercareerstats.PlayerCareerStats(player_id=player_to_get[0]['id'], per_mode36='Totals')
                
                player_stats_career = json.loads(player_stats.get_json())['resultSets'][1]
                            
                players_dict_with_stats[player_to_get[0]['full_name']] = player_stats_career['rowSet'][0]

                to_remove = ['PLAYER_ID', 'LEAGUE_ID', 'Team_ID']
            
                for to in to_remove:
                    player_stats_career['headers'].remove(to)
                
                for i in range(3):
                    players_dict_with_stats[player_to_get[0]['full_name']].pop(i)
                
                career_total_points = 0
                career_total_assits = 0
                career_total_rebounds = 0
                
            player_first_name = player_to_get[0]['first_name']
            player_last_name = player_to_get[0]['last_name']
                        
            if player_to_get[0]['is_active'] == True:
                url = f'https://nba-players.herokuapp.com/players/{player_last_name}/{player_first_name}'
                
                url_player_stats = f'https://nba-players.herokuapp.com/players-stats/{player_last_name}/{player_first_name}'
                
                api_call = requests.get(url_player_stats)
                
                team_name = api_call.json()['team_name']

                dict_of_player_stats = {
                    'ppg': api_call.json()['points_per_game'],
                    'fgp': api_call.json()['field_goal_percentage'],
                    'ftp': api_call.json()['free_throw_percentage'],
                    'tpp': api_call.json()['three_point_percentage'],
                    'rpg': api_call.json()['rebounds_per_game'],
                    'apg': api_call.json()['assists_per_game'],
                    'spg': api_call.json()['steals_per_game'],
                    'bpg': api_call.json()['blocks_per_game'],
                    'tpg': api_call.json()['turnovers_per_game'],
                    'per': api_call.json()['player_efficiency_rating']
                }   
                        
                my_file = Path(settings.STATIC_URL + f'player_imgs/{player_first_name}_{player_last_name}.png')
                
                if not my_file.exists():
                        
                    api_call = requests.get(url)
            
                    file = open(f"static/player_imgs/{player_first_name}_{player_last_name}.png", "wb")
                    file.write(api_call.content)
                    file.close()
                
                img_url = settings.STATIC_URL + f"player_imgs/{player_first_name}_{player_last_name}.png"
                    
            context = {
                'player': player_to_get[0],
            }
            
            if player_to_get[0]['is_active'] == False:
                context['stats'] = players_dict_with_stats
                context['headers'] = player_stats_career['headers']
                            
            if player_to_get[0]['is_active'] == True:
                context['url'] =  img_url
                context['team'] = team_name
                context['player_season_stats'] = dict_of_player_stats
        
            return render(request, self.template_name, context=context)
        else:
            messages.add_message(request, messages.ERROR, "Sorry, that player is not recognized. Please try again!")
            return HttpResponseRedirect(reverse('home:home'))
class InactiveSearch(View):
    
    template_name = 'home/archive_search.html'
    
    def get(self, request, *args, **kwargs):
        
        players_dict = players.get_players()

        refined_players = []
    
        for player in players_dict:
            if player['is_active'] == False:
                refined_players.append(player)

        paginator = Paginator(refined_players, 60)
        
        page_number = request.GET.get('page')
        
        page_obj = paginator.get_page(page_number)
        
        context = {
            'players': page_obj,
            'paginator': paginator,
            'range': len(refined_players)
        }
        
        return render(request, self.template_name, context=context)
        

home/templates/home/archive_search.html
{% extends 'home/base.html' %}

{% load static %}

{% block content %}

    <div class = "col-sm-12">
        <table class="table" style="width: 100px;">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Activity</th>
                </tr>
            </thead>
            <tbody>
                {% for player in players %}
                    <tr>
                        <td>{{ player.full_name }}</td>
                        <td>{{ player.is_active }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    <div class="pagination" style="justify-content: center; margin-bottom: 1%">   
        {% for p in paginator.page_range %}            
            <li class="page-item"><a id = '' class="page-link" href='?page={{ p }}'>{{ p }}</a></li>
        {% endfor %}
    </div>

    <style>
        table th {
            width: auto !important;
        }
    </style>
{% endblock %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <title>NBA App</title>
    <meta name="viewport" content="user-scalable=no,width=device-width, initial-scale=1"/>
    <meta name = "mobile-web-app-capable" content="yes">
	<meta name = "apple-mobile-web-app-capable" content="yes">
    
    <link rel="apple-touch-icon" sizes = "300x300" href = "{% static 'favicon/favicon.ico' %}">
    <link id = "favicon" rel="shortcut icon" sizes = "300x300" href="{% static 'favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet"  type='text/css'>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

    <nav id = "nav" class="navbar navbar-expand-lg navbar-dark"> 
        <a class="navbar-brand" href="{% url 'home:home' %}" id = "head" style="color: white;">NBA Stats<img class = "icon_img" src = "{% static 'favicon/favicon.ico' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon" style= "color: white;"></span>
        </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class = "nav-item">
                        <a class="nav-link" href="{% url 'home:inactive_search' %}" style = "color: white;" role="button" aria-haspopup="true" aria-expanded="false" disabled>
                            Archive Search </i>
                        </a>
                    </li>
                </ul>
                <ul class = "navbar-nav ml-auto">
                    <li class = "nav-item">
                        <a class="nav-link" href="" style = "color: white;" role="button" aria-haspopup="true" aria-expanded="false" disabled>
                            Login <i class = "fa fa-sign-in"></i>
                        </a>
                    </li>
                </ul>
                <ul class = "navbar-nav">
                    <li class = "nav-item">
                        <a class="nav-link" href="" style = "color: white;" role="button" aria-haspopup="true" aria-expanded="false" disabled>
                            Sign Up <i class = "fa fa-plus"></i>
                        </a>      
                    </li>
                </ul>
            </div>
    </nav> 
    {% block content %}
        <body></body>
    {% endblock %}

    <style>
        #nav{
            background-color: #428bca;
        }
        .icon_img{
            height: 30px;
            width: 30px;
        }
    </style>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

<link rel = "stylesheet" type="text/css" href = "{% static 'styles/home/home_style.css' %}">

<script>AOS.init()</script>

<div class = "main-block" id = "image">
    <form class = "" action = "" method="GET">
        <h1 class = "title">Finding Players just got <span id = "easier">fun</span>.</h1><br>
        <div class = "input-group">
            {{ form.player_name }}
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit" name="search">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div><br>
    </form>
    {% include 'home/messages.html' %}
    <br>
    <br>
</div>

<div class="row align-items-end">
    <div class="col-sm-6">
        <img src = "{% static 'player_imgs/LeBron_James.png' %}" id = "main_img_1">
    </div>
    <div class = "col-sm-6" id = "info_1" data-aos="slide-up">
        <h1 id = "fader_title_1">
            Stats from all the <span id = "easier">teams</span>
        </h1>
        <p id = "sub-text">
            Get up-to-date stats from all <span id = "easier">30</span> teams around the league
        </p>
    </div>
</div>

<div class="row align-items-center">
    <div class = "col-sm-6" id = "info_1" data-aos="slide-up">
        <h1 id = "fader_title_1">
            Find the <span id = "easier">perfect</span> player
        </h1>
        <p id = "sub-text">
            With <span id = "easier">NBA Stats</span> you'll be able to search 
            for all your favourite players.<br><br>
            
            You can also <span id = "easier">build lineups</span> and save them
        </p>
    </div>

    <div class="col-sm-6" data-aos="fade-left">
        <img src = "{% static 'player_imgs/Carmelo_Anthony.png' %}" id = "main_img_1">
    </div>
</div>

<br>

<div class="most_searched" data-aos="slide-up">
    <h1 class = "title" style="color: black; text-align: center;">Most searched players in the NBA</h1>
    <div class="card-deck">
        {% for player, details in players.items %}
            <div class="card" id = "recipe">
                <a id = "recipe_id" href="">
                    <img class="card-img-top" src="{{ details.url }}" alt="Card image cap" height="250" width="100">
                </a>
                <div class="card-body" id = "player_details">
                    <h5 class="display-2" style="font-size: 1.3rem;">{{ player }}</h5>
                    <p class="display-2" style="font-size: 1.3rem;">{{ details.searches }} searches</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<br>


<div class = "col-sm-12 align-items-center" id = "divider">
    <div class="text" data-aos="slide-up">
        <h2 class="small_title">With all of the NBA players and teams</h2>
        <br><br>
        <h2 class = "small_title">You'll be sure to find a stat that you love</h2>
        <br>
    </div>
</div>    

<div class = "bottom-info">
    <div class="row align-items-center">
        <div class = "col-sm-6" id = "dev-details">
            <h3 class = "small_title" style="color: black; text-align: center;">
                NBA Stats <img id = "bottom_img" src = "{% static 'favicon/favicon.ico'%}">
            </h3>
            <p>Developed and Owned by Andrew Hyslop</p>
        </div>

    </div>
</div>

<script>
    const div=document.getElementById("image");
    let images = ["{% static 'lebron.jpeg' %}","{% static 'melo.jpeg' %}", "{% static 'kobe.jpeg' %}"]
    let counter = 0;


    function volgendefoto() {
        counter++;
        if (counter > 2) {
            counter = 0
        }
                    
        var string = "url(" + images[counter] + ")";

        div.style.backgroundImage=string;
    }

    setInterval(volgendefoto, 3000);
</script>    
<style>
    .main-block{
        background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.3)),url("{% static 'lebron.jpeg' %}");
        background-size: cover;
        height: 400px;
    }   
</style>
{% endblock %}

home/templates/home/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="container-fluid p-0" style="width: 80%; z">
            <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

home/templates/home/player_detail.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    
    <link rel = "stylesheet" type="text/css" href = "{% static 'styles/home/player_detail.css' %}">

    <div class = "jumbotron">
        <h1>{{ player.full_name }}</h1>
        <h3>{{ team }}</h3>
        <img src = "{{ url }}" id = "player_img">
        <br>
        {% if player_season_stats %}
            <h5 id = "stats">PPG:
                {% for k, v in player_season_stats.items %}
                    {% if k == 'ppg' %}
                        {{ v }}
                    {% endif %}
                {% endfor %}

                APG:
                {% for k, v in player_season_stats.items %}
                    {% if k == 'apg' %}
                        {{ v }}
                    {% endif %}
                {% endfor %}

                RPG:
                {% for k, v in player_season_stats.items %}
                    {% if k == 'rpg' %}
                        {{ v }}
                    {% endif %}
                {% endfor %}
            </h5>
            
            <div class = "btn-toolbar" id = "btns">
                <button id = "detailed_stats" class = "btn btn-success">Detailed Stats</button>
                &nbsp;
                <button id = "add_player_to_lineup" class = "btn btn-success">Add {{ player.first_name }} to your lineup</button>              
            </div>
        {% else %}
            <h3>Career Points:
                {% for k, v in stats.items %}
                    {% if k == 'ppg' %}
                        {{ v }}
                    {% endif %}
                {% endfor %}

                Career Assists:
                {% for k, v in player_season_stats.items %}
                    {% if k == 'apg' %}
                        {{ v }}
                    {% endif %}
                {% endfor %}

                Career Rebounds:
                {% for k, v in player_season_stats.items %}
                    {% if k == 'rpg' %}
                        {{ v }}
                    {% endif %}
                {% endfor %}
            </h3>
        {% endif %}
        
    </div>

{% endblock %}